package com.signbridge.backend.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Translation Entity
 *
 * Represents a completed ASL translation.
 *
 * This entity will be stored in PostgreSQL
 * inside the "translations" table.
 *
 * Example:
 *
 * ASL Gloss:
 * STORE I GO TOMORROW
 *
 * English Translation:
 * I am going to the store tomorrow.
 */
@Entity
@Table(name = "translations")
public class Translation {

    /**
     * Primary Key
     *
     * Auto-generated by PostgreSQL.
     *
     * Example:
     * 1
     * 2
     * 3
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Original ASL gloss produced
     * by the Transformer model.
     *
     * Example:
     * STORE I GO TOMORROW
     */
    @Column(nullable = false, length = 1000)
    private String aslGloss;

    /**
     * Natural English sentence generated
     * by OpenAI.
     *
     * Example:
     * I am going to the store tomorrow.
     */
    @Column(nullable = false, length = 2000)
    private String englishSentence;

    /**
     * Timestamp when the translation
     * was created.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Default constructor required by JPA.
     */
    public Translation() {
    }

    /**
     * Constructor used when creating
     * a new Translation object.
     */
    public Translation(
            String aslGloss,
            String englishSentence,
            LocalDateTime createdAt) {

        this.aslGloss = aslGloss;
        this.englishSentence = englishSentence;
        this.createdAt = createdAt;
    }

    /**
     * Returns database ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets database ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns original ASL gloss.
     */
    public String getAslGloss() {
        return aslGloss;
    }

    /**
     * Sets ASL gloss.
     */
    public void setAslGloss(String aslGloss) {
        this.aslGloss = aslGloss;
    }

    /**
     * Returns translated English sentence.
     */
    public String getEnglishSentence() {
        return englishSentence;
    }

    /**
     * Sets translated English sentence.
     */
    public void setEnglishSentence(String englishSentence) {
        this.englishSentence = englishSentence;
    }

    /**
     * Returns creation timestamp.
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets creation timestamp.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Useful for debugging and logging.
     */
    @Override
    public String toString() {
        return "Translation{" +
                "id=" + id +
                ", aslGloss='" + aslGloss + '\'' +
                ", englishSentence='" + englishSentence + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}